# -*- coding: utf-8 -*-
"""Wildfire_exploratory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14FjiYJQhU_JTiQL5Wl1vb3MW8K6PNnIu
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/COMP4710/data-cleaned.csv')
df.drop(labels="true_cause", axis=1, inplace=True)

# dataset general info
df.info()

categorical = [var for var in df.columns if df[var].dtype=='O']
numerical = [var for var in df.columns if var not in categorical]

# clean up categorical null variable
for var in categorical:
  df[var]= df[var].fillna("N/A")
  print(df[var].value_counts())


# clean up numerical null variable using median
for var in numerical:
  df[var] = df[var].fillna(df[var].median())
print(categorical)
print(numerical)

df.shape

# global data visualization
import matplotlib.pyplot as plt
import seaborn as sns

f,ax=plt.subplots(figsize=(18,8))
ax.pie(df['isNaturalCaused'].value_counts(),labels=["Human Caused", "Natural Caused"], explode=[0,0],autopct='%1.1f%%',shadow=True)
ax.set_title('Natural vs Non Natural Caused Wild fire')

plt.show()

f,ax=plt.subplots(figsize=(18,8))
ax = df['general_cause_desc'].value_counts().plot.pie(autopct='%1.1f%%',shadow=True, labeldistance=None)
ax.set_title('Fine grained categorization')

plt.legend()
plt.plot()

f, ax = plt.subplots(figsize=(10, 8))
ax = sns.countplot(x="fire_year", hue="isNaturalCaused", data=df, palette="Set1",)
ax.set_title("Fire cases through years")
ax.legend(["Human Caused", "Natural Caused"])
plt.show()

f, ax = plt.subplots(figsize=(25, 8))
ax = sns.countplot(x="fire_year", hue="general_cause_desc", data=df, palette="Set1", width=1)
ax.set_title("Fire causes through years")
plt.show()

fig = plt.figure(figsize =(10, 7))

# Creating plot
plt.boxplot(df["fire_spread_rate"])

# show plot
plt.show()
df["fire_spread_rate"].head()

# box plot of numerical variable
data_natural = df.loc[df["isNaturalCaused"] == 1]
data_human = df.loc[df["isNaturalCaused"] == 0]

data_list = {"all": df,"natural": data_natural, "human": data_human}

f, ax = plt.subplots(len(numerical) - 2, len(data_list.keys()),figsize=(25, 60))
column_ax = 0
row_ax = 0
for frame_name in data_list.keys():
  data = data_list[frame_name]

  for header in numerical:
    if(header != "fire_year" and header !="isNaturalCaused"):
      axes = ax[row_ax, column_ax]
      axes.boxplot(data[header])
      axes.set_title(f"box plot for {header} for {frame_name} fire cause")
      row_ax+=1
  column_ax += 1
  row_ax = 0

for axes in ax.flat:
    axes.set_yscale('log')
plt.show()

f, ax = plt.subplots(len(categorical) - 1, len(data_list.keys()),figsize=(25, 25))
column_ax = 0
row_ax = 0
for frame_name in data_list.keys():
  data = data_list[frame_name]
  for header in categorical:
    if header != "general_cause_desc":
      axes = ax[row_ax, column_ax]
      axes = data[header].value_counts().plot.pie(autopct='%1.1f%%',ax=axes,shadow=True)
      axes.set_title(f"box plot for {header} for {frame_name} fire cause")
      row_ax +=1
  column_ax += 1
  row_ax = 0

plt.show()